# Generated by Django 4.2.21 on 2025-07-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_appointmenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenthistory',
            name='avaliacao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmenthistory',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
